exports.getCommentSQL = 
`SELECT ID, USER_ID,CONTENT FROM CONTENT
WHERE PERSONAL = TRUE AND
FEED = TRUE AND
COMMENT = TRUE AND
FEED_ID = $1
USER_ID = $2 ORDER BY id ASC
`

// exports.getTextFeedSQL = 
// `SELECT CONTENT FROM CONTENT
// WHERE PERSONAL = TRUE AND
// FEED = TRUE AND
// TXT = TRUE AND
// USER_ID = $1
// `

// exports.getPhotoFeedSQL = 
// `SELECT CONTENT FROM CONTENT
// WHERE PERSONAL = TRUE AND
// FEED = TRUE AND
// PHOTOANDTEXT = TRUE AND
// USER_ID = $1
// `

exports.postCommentSQL = 
`INSERT INTO CONTENT (CONTENT,USER_ID,PERSONAL,TXT,FEED,COMMENT,PHOTOANDTEXT)
VALUES($1,$2,TRUE,$3,TRUE,FALSE,$4)
`

exports.putCommentSQL = 
`UPDATE CONTENT
SET CONTENT = $1,
TXT = $2,
PHOTOANDTEXT = $3
WHERE ID = $4
`

exports.deleteCommentSQL = 
`DELETE FROM CONTENT
WHERE ID = $1
`